# Generated by Django 6.0.6 on 2026-06-19 09:23

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sellerprofile_address_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration_data', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SellerDeletionRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Seller Deletion Request',
                'verbose_name_plural': 'Seller Deletion Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
