# Generated by Django 6.0.6 on 2026-06-26 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pendinguser_sellerdeletionrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreed_to_privacy_policy',
            field=models.BooleanField(default=False),
        ),
    ]
