# Generated by Django 6.0.6 on 2026-06-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_agreed_to_privacy_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='order_message_template',
            field=models.TextField(blank=True, default=''),
        ),
    ]
