# Generated by Django 6.0.6 on 2026-06-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_buyerprofile_order_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='quick_replies',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='quick_replies',
            field=models.TextField(blank=True, default=''),
        ),
    ]
