# Generated by Django 6.0.6 on 2026-06-26 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_buyerprofile_quick_replies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='company_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CompanyLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='accounts.sellerprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
    ]
