# Generated by Django 6.0.6 on 2026-06-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sellerprofile_company_description_companylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
