# Generated by Django 6.0.6 on 2026-06-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sellerprofile_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='order_approve_message_template',
            field=models.TextField(blank=True, default=''),
        ),
    ]
