# Generated by Django 6.0.6 on 2026-07-12 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_sellerprofile_order_approve_message_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='business_doc',
            field=models.FileField(blank=True, null=True, upload_to='business_docs/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='passport_image',
            field=models.FileField(blank=True, null=True, upload_to='seller_passports/'),
        ),
        migrations.CreateModel(
            name='KYCSelfie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfie_center', models.ImageField(blank=True, null=True, upload_to='kyc_selfies/')),
                ('selfie_left', models.ImageField(blank=True, null=True, upload_to='kyc_selfies/')),
                ('selfie_right', models.ImageField(blank=True, null=True, upload_to='kyc_selfies/')),
                ('selfie_up', models.ImageField(blank=True, null=True, upload_to='kyc_selfies/')),
                ('selfie_down', models.ImageField(blank=True, null=True, upload_to='kyc_selfies/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_selfie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
