# Generated by Django 6.0.6 on 2026-07-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_sellerprofile_business_doc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnverifiedSeller',
            fields=[
            ],
            options={
                'verbose_name': 'Unverified Seller',
                'verbose_name_plural': 'Unverified Sellers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.sellerprofile',),
        ),
    ]
