# Generated by Django 6.0.6 on 2026-06-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crmcalculation',
            name='percentage',
        ),
        migrations.AddField(
            model_name='crmcalculation',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='crmcalculation',
            name='value_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('USD', 'USD')], default='PERCENTAGE', max_length=15),
        ),
    ]
