# Generated by Django 6.0.6 on 2026-07-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_crmcalculation_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmcalculation',
            name='value_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('USD', 'USD'), ('UZS', 'UZS')], default='PERCENTAGE', max_length=15),
        ),
    ]
