# Generated by Django 6.0.6 on 2026-08-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_crmcalculation_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmcalculation',
            name='basis',
            field=models.CharField(choices=[('PER_PRODUCT', 'Per Product'), ('PER_SALES', 'Per Sales')], default='PER_SALES', max_length=20),
        ),
    ]
