# Generated by Django 6.0.6 on 2026-08-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Русский'), ('uz', 'Oʻzbekcha')], default='en', max_length=10),
        ),
    ]
