# Generated by Django 6.0.6 on 2026-06-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_variants_info',
            field=models.TextField(blank=True, default=''),
        ),
    ]
