# Generated by Django 6.0.6 on 2026-07-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='manufacturing_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
