# Generated by Django 6.0.6 on 2026-06-26 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcomment_productlike_savedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_description_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_images', to='products.product')),
            ],
        ),
    ]
