# Generated by Django 6.0.6 on 2026-06-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productdescriptionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturing_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
