# Generated by Django 6.0.6 on 2026-06-27 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_manufacturing_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='review_media/'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='products.productreview'),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='rating',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.DeleteModel(
            name='ProductComment',
        ),
    ]
