# Generated by Django 6.0.6 on 2026-07-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('UZS', 'Uzbekistan Som')], default='UZS', max_length=3),
        ),
    ]
