# Generated by Django 6.0.6 on 2026-07-20 06:45

from django.db import migrations, models


def copy_name_to_name_en(apps, schema_editor):
    """Copy the existing `name` value into `name_en` for every category."""
    Category = apps.get_model('products', 'Category')
    for cat in Category.objects.all():
        if not cat.name_en:
            cat.name_en = cat.name
            cat.save(update_fields=['name_en'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productvariant_additional_manufacturing_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название (Русский)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(blank=True, max_length=100, verbose_name="Name (O'zbek)"),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        # Data migration: populate name_en from existing name
        migrations.RunPython(copy_name_to_name_en, noop),
    ]
